version: "3.8"
services:
  nuwe-chall-api:
    build:
      context: .
      dockerfile: Dockerfile.maven
    image: nuwe-chall-api-image:v1
    container_name: nuwe-chall-api-container
    ports:
      - "8080:8080"
    depends_on:
      - nuwe-chall-mysqldb
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://nuwe-chall-mysqldb:3306/accwe-hospital"
    networks:
      - nuwe-chall-net

  nuwe-chall-mysqldb:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    image: nuwe-chall-db-image:v1
    container_name: nuwe-chall-db-container
    ports:
      - "3307:3306"
    networks:
      - nuwe-chall-net

volumes:
  nuwe-chall:

networks:
  nuwe-chall-net:
    driver: bridge
